@startuml

skinparam classAttributeIconSize 0

  package "PlayerAudience-Client" <<Rectangle>>{  
    class "PlayerAudienceClientExchange" as pace <<Observer>>{
      {field} -sessionCookie: Cookie
      {field} -votingAllowed: bool
      {field} -selectedDecision: int
      {field} -possibleDecisions: Dictionary<Guid, string>
      {method} +PlayerAudienceClientExchange()
      {method} +Update(): void
      {method} -HashifyStringToID(decision: string): int
    }

    class "PlayerAudienceView" as pav {
      {method} +PlayerAudienceView()
    }
  }  


@enduml