@startuml
() "HTTP" as http
() "API" as api
() "User\nInterface" as ui
() "Moderator\nInterface" as mi
[PlayerAudience-Client] <<component>> as AuCl
[Server-Client] <<component>> as SeCl
[Moderator-Client] <<component>> as StPlCl

ui -up- AuCl
http - SeCl
AuCl -> http
api <-> StPlCl
SeCl <-> api
mi -up- StPlCl

@enduml