@startuml
skinparam classAttributeIconSize 0

package "PlayerAudience Client"{
    
  class "PlayerAudienceClientExchange" as pace <<interface>>{
    {field} +websocket: WebSocket
    {field} +ip: int
    {field} +port: int
    {method} +PlayerAudienceClientExchange(ip: int, port: int)
    {method} +requestCurrentPossibleDecisions(): StoryEvent[]
    {method} +checkJSON(): boolean
  }

  class "PlayerAudienceView" as pav {
    {method} +PlayerAudienceView()
  }

  class "WebSocket" as ws {
    {field} +CloseStatus
    {field} +CloseStatusDescription
    {field} +DefaultKeepAliveInterval
    {field} +State
    {field} +SupProtocol
    {method} +Abort()
    {method} +CreateClientBuffer(Int32, Int32)
    {method} +ReceiveAsync(Memory<Byte>, Cancellation Token)
    {method} +SendAsync(ArraySegment<Byte>, WebSocketMessageType, Boolean, CancellationToken)
  }

}

pace - pav
ws - pace
@enduml