site_name: Technical Specifications
nav:
 - QualityQuest: index.md
 - Glossar: glossar.md
 - Requirements: requirements.md
 - Use-Case: use-case-diagramme.md
 - StoryFlow: storyflow.md
 
 
theme: readthedocs

markdown_extensions:
 - admonition
