site_name: Technical Specifications
nav:
  - Quality Quest: index.md
  - Table of content: toc.md
  - Glossary: glossary.md
  - Requirements: requirements.md
  - Use-Cases: use-case-diagramme.md
  - StoryFlow: storyflow.md
  - Used Tools, Plugins and Libraries: usedtools.md
  - Change history: changehistory.md

theme: 
  readthedocs

markdown_extensions:
  - admonition
