site_name: Technical Specifications
nav:
  - Quality Quest: index.md
  - Table of content: toc.md
  - Glossary: glossary.md
  - Requirements: requirements.md
  - Use-Cases: use-case-diagramme.md
  - Architecture diagrams: architectureDiagrams.md
  - Network protocol: network-protocol.md
  - StoryFlow: storyflow.md
  - Used tools, plugins and libraries: usedtools.md
  - Change history: changehistory.md

theme: 
  readthedocs

markdown_extensions:
  - codehilite
  - admonition