@startuml
(*) --> "A bug has surfaced."
--> "So far no one else has found the bug."
if "How do you proceed?" then 
--> [You write a bug ticket.] "Yaggaya sees the ticket \n and passes it on to the appropriate place. \n Your stats change: \n +2 analytics" as bugTicket
else
--> [Just ignore it, \n no one will notice anyway.] if "dice roll > 3" then
--> [true] "The bug leads to a critical error."
--> "The bug was found and Yaggaya is pretty mad at you because you should have noticed the bug, since you worked on the code last. \n Your stats change: \n -3 communication \n -3 analytics" as badEnd

else
--> [false] "The bug does not lead to any critical error."
--> "The bug remains undetected. \n Your stats change: \n -3 analytics" 
-[#blue,dotted]-> "The project customer calls again \n and wants to have a completely new feature implemented." as nextDecision 
endif
badEnd -[#blue,dotted]-> nextDecision
bugTicket -[#blue,dotted]-> nextDecision
@enduml