@startuml

box "Network protocol relevance" #LightSteelBlue
actor "Moderator-Client" as m order 1
database "ServerLogic" as s order 2
end box



activate m
activate s

loop send until answered 
    m -> s: WebSocket Ping
end 

s --> m: WebSocket ACK

opt 
    m -> s: Reconnect
    s --> m: ReconnectSuccessful
end


@enduml