@startuml

() "Moderator\nInterface" as mi
() "WebSocket" as API

component "Moderator-Client" <<component>> as ac{

    component "Logic" <<subsystem>> as lg {
        [StoryGraph] <<subsystem>> as sg
        [PollEvaluator] as pe
    }
    
    [ModeratorView] <<subsystem>> as mv
}

API -up- pe
mv -right- sg
mv - pe
mi -up- mv


@enduml
