@startuml
() "HTTP" as http
() "WebSocket" as api

component "Server" <<component>> as server{
component "Logic" <<component>> as logic{
    [Networking] <<subsystem>> as network
    [Message Managment] <<subsystem>> as message
}
}
http -right- network


network <-> message

api -up- network
@enduml