@startuml
(*) --> "Character selection"
if "" then
--> [character 1] "Elective course" as wpf
else
--> [character 2] wpf
else
--> [character 3] wpf
else
--> [character 4] wpf
else
--> [character 5] wpf
else
--> [character 6] wpf
if "" then
--> [Introduction\nto Bali] "Company internship" as fpr
else
--> [Requirements\nEngineering] fpr
else
--> [Introduction to\nSoftware Architectures] fpr
else
--> [Usability as\nsuccess factor] fpr
if "" then
-> [yes] "Gain experience" as n
n -> "Graduation" as p
else
--> [no] p
p --> "First project" as ep
ep --> "First task" as ea
if "" then
--> [Ask\nmentor] "Write tests" as ts
else
--> [Search the internet] ts
else
--> [Just\ngo for it] ts
if "" then
--> [thoroughly] "Attend\nchristmas party" as fd
else
--> [only till\ndeadline] fd
if "" then
-> [attend] "Christmas party" as cp
else
--> [do not attend] "Continue working\n/Fix issues" as cw
cp --> if "" then
--> [Sit alone] "Drink something" as dri
else
--> [Chat with\ncolleagues] "Level up\nprogramming" as lvl
lvl --> dri
else
--> [Chat with\nsupervisors] "Unlock dialouge options" as sup
sup --> dri
if "" then
--> [Strong alcohol] "Negative effect" as bad
else
--> [Weak alcohol] "No negative\neffects" as non
else 
--> [Non-alcholic] non
bad --> "Voluntary training" as vt
non --> vt
cw --> vt
if "" then
--> [Go on holiday] "Modification requests\nfrom customers" as a
else
--> [No] a
else
--> [Yes] "Improve expertise" as ex
ex --> a
if "" then
--> [implement] "Bug detected" as be
else
--> [do not\nimplement] be
else
--> [hang up] be
if "" then
--> [write bugticket\n] "Spontaneous feature\nfrom customers" as a2
else
--> [ignore] a2
if "" then
--> [implement] "support colleague" as ku
else
--> [ask] "Modification process" as x
if "" then
--> [alone] ku
else
--> [discuss] ku
if "" then
--> [help] "Code Review" as cr
else
--> [not help] cr
if "" then
--> [yes] "Workshop\non Hawaii" as ws
else
--> [no] ws
ws --> (*)
@enduml