@startuml
"   " -[#blue,dotted]-> Voluntary training"
if "" then
--> [Go on holiday] "Modification requests\nfrom customers" as a
else
--> [No] a
else
--> [Yes] "Improve expertise" as ex
ex --> a
if "" then
--> [implement] "Bug detected" as be
else
--> [do not\nimplement] be
else
--> [hang up] be
if "" then
--> [write bugticket\n] "Spontaneous feature\nfrom customers" as a2
else
--> [ignore] a2
if "" then
--> [implement] "support colleague" as ku
else
--> [ask] "Modification process" as x
if "" then
--> [alone] ku
else
--> [discuss] ku
if "" then
--> [help] "Code Review" as cr
else
--> [not help] cr
if "" then
--> [yes] "Workshop\non Hawaii" as ws
else
--> [no] ws
ws --> (*)
@enduml