@startuml
() "User\nInterface" as ui

component "Server" <<device>> as sl{
    () " " as api

    component "PlayerAudience-Client" <<component>> as ac{
        [GUI] <<subsystem>>
        [Logic] <<subsystem>>
        () " " as empty
    }

    [ServerLogic] <<component>> as server


}
ui )-up- GUI
empty -left- Logic
GUI -left-( empty
Logic -down-( api
api -server

@enduml
