@startuml
() "User\nInterface" as ui
() "API" as api

component "PlayerAudience-Client" <<component>> as ac{
    [GUI] <<subsystem>>
    [Logic] <<subsystem>>
    () " " as empty
}

ui )-up- GUI
empty - Logic
GUI -( empty
Logic -down-( api

@enduml
