@startuml

skinparam classAttributeIconSize 0

package "Moderator-Client" {

  class StoryEvent {
    {field} +eventId: int
    {field} +description: string
    {field} +parent: StoryEvent
    {field} +children: StoryEvent[]
    {method} +StoryEvent(parent: StoryEvent, id: int)
    {method} +addChild(): void
  }

  class StoryGraph {
    {field} +id: int
    {field} +character: Character
    {field} +root: StoryEvent
    {field} +currentEvent: StoryEvent
    {method} +StoryGraph(id: int)
    {method} +loadGraphFromFile(): Graph
    {method} +saveGraphToFile(): void
    {method} +getNextPossibleEvent(): StoryEvent[]
    {method} +setCurrentEvent(newCurrentEvent: StoryEvent): void
    {method} +getNextStoryEventById(id: int): StoryEvent
  }

  class Skill {
    {field} +id: int
    {field} +value: int
    {field} +description: string
    {method} + Skill(id: int, val: int, desc: string)
    {method} + setValue(val: int): void
    {method} + getValue(): int
  }

  class Character {
    {field} +sprite: Texture
    {field} +abilities: Skill[]
    {field} +name: string
    {method} +Character()
  }

  class "ModeratorView" as mf {
    {field} +timeoutDuration: int
    {method} +ModeratorView()
    {method} +pausePolling(val: boolean): void
    {method} +offlineMode(val: boolean): void
  }

  class "PollEvaluator" as pe {

    {field} possibleDecisions: StoryEvent[]
    {field} timeout: int
    {field} voteCounter: int[]
    {method} +PollEvaluator()
    {method} +checkServerStatus(): void
    {method} +broadcastNextDecision(): void
    {method} +evaluateVotes(): int
    {method} +addVote(): void
  }

  class "ModeratorClientExchange" as mcei{
    {field} +websocket: WebSocket
    {field} +authentificationTokenModeratorClient: Token
    {method} +ModeratorClientExchange()
    {method} +getCurrentPollEval(): int
    {method} +makeJSON(): string
  }
  
  StoryEvent "n" --* "1" StoryGraph
  StoryGraph -- mf
  StoryGraph -- Character
  Character "1" *-- "n" Skill
  mf -- pe
  pe -- mcei
}

package "Server" {
   class "API" as api {
        {field} +observerCollection: Observer
        {method} +API()
        {method} +registerObserver(observer: Observer, cookie: Cookie): void
        {method} +unregisterObserver(observer: Observer): void
        {method} +notifyObservers(): void
        {method} +updatePossibleDecisions(): void
        {method} +collectVotes(): void
  }

  package "Backend" <<Rectangle>>{
    class "ServerShell" as ss {
      {field} +Logger: Logger
      {field} +port: int
      {field} +runShell: boolean
      {field} +serverShell: ServerShell
      {field} +capacity: int
      {field} +bufferedReader: BufferedReader
      {method} +ServerShell()
      {method} +startShell(): void
      {method} +stopShell(): void
      {method} +parseCommand(command: string): void
      {method} +showHelp(): void
      {method} +configPort(): void
      {method} +configCapacity(): void
      {method} +startServer(): void
      {method} +stopServer(): void
      {method} +main(args: string[]): void
    }

    class "ModeratorClientManager" as cm {
      {field} +webSocket: WebSocket
      {field} +ip: int
      {field} +port: int
      {field} +logger: Logger
      {field} +authentificationTokenModeratorClient: Token
      {method} +ModeratorClientManager(session: Session): void
      {method} +disconnect(): void
      {method} +onDisconnect(): void
      {method} +recieve(message: string): void
      {method} +checkJSON(message: string): void
      {method} +sendMessage(message: string): void
      {method} +send(message: string): void
      {method} +recieve(message: string): void
    }    

    class "MainServerLogic" as msl {
      {field} +moderator: WebClient
      {field} +logger: Logger
      {method} MainServerLogic(capacity: int, port: int)
      {method} +onFalseMessage(message: string): void
      {method} +onVotingMessage(message: string): void

    }

    class "ServerLogger" as sl {
      {field} +globalLogger: Logger
      {field} +logFile: FileHandler
      {field} +isSetup: Boolean
      {field} +consoleHandler: Handler
      {method} +Logger()
      {method} +setup(): void
      {method} +addHandler(logger: Logger): void
      {method} +setLevel(level: int): void
      {method} +setConsoleOutput(val: boolean): void
    }
  }
  package "PlayerAudience-Client" <<Rectangle>>{  
    class "PlayerAudienceClientExchange" as pace <<Observer>>{
      {field} +sessionCookie: Cookie
      {field} +hasVoted: boolean
      {field} +selectedDecision: StoryEvent
      {field} +possibleDecisions: StoryEvent[]
      {method} +PlayerAudienceClientExchange()
      {method} +update(): void
      {method} +sendSelectedDecision(): StoryEvent 
    }

    class "PlayerAudienceView" as pav {
      {method} +PlayerAudienceView()
    }
  }
  ss -- msl
  msl - cm
  msl -left- api
  sl ... cm
  sl ... msl
  sl ... api
  sl ... ss
  pace - pav
  api "1" <-up- "n" pace : observes
}

mcei - cm

@enduml