@startuml

skinparam classAttributeIconSize 0

package "Server" {
   class "API" as api {
        {field} +observerCollection: Observer
        {method} +API()
        {method} +registerObserver(observer: Observer, cookie: Cookie): void
        {method} +unregisterObserver(observer: Observer): void
        {method} +notifyObservers(): void
        {method} +updatePossibleDecisions(): void
        {method} +collectVotes(): void
  }

  package "Backend" <<Rectangle>>{
    class "ServerShell" as ss {
      {field} +logger: Logger
      {field} +port: int
      {field} +runShell: boolean
      {field} +serverShell: ServerShell
      {field} +capacity: int
      {field} +bufferedReader: BufferedReader
      {method} +ServerShell()
      {method} +startShell(): void
      {method} +stopShell(): void
      {method} +parseCommand(command: string): void
      {method} +showHelp(): void
      {method} +configPort(): void
      {method} +configCapacity(): void
      {method} +startServer(): void
      {method} +stopServer(): void
      {method} +main(args: string[]): void
    }

    class "ModeratorClientManager" as cm {
      {field} +webSocket: WebSocket
      {field} +ip: int
      {field} +port: int
      {field} +logger: Logger
      {field} +authentificationTokenModeratorClient: Token
      {method} +ModeratorClientManager(session: Session): void
      {method} +disconnect(): void
      {method} +onDisconnect(): void
      {method} +recieve(message: string): void
      {method} +checkJSON(message: string): void
      {method} +sendMessage(message: string): void
      {method} +send(message: string): void
      {method} +recieve(message: string): void
    }    

    class "MainServerLogic" as msl {
      {field} +moderator: WebClient
      {field} +logger: Logger
      {method} MainServerLogic(capacity: int, port: int)
      {method} +onFalseMessage(message: string): void
      {method} +onVotingMessage(message: string): void

    }

    class "PollEvaluator" as pe {
    {field} possibleDecisions: StoryEvent[]
    {field} voteCounter: int[]
    {method} +PollEvaluator()
    {method} +evaluateVotes(): int
    {method} +addVote(): void
  }

    class "ServerLogger" as sl {
      {field} +globalLogger: Logger
      {field} +logFile: FileHandler
      {field} +isSetup: Boolean
      {field} +consoleHandler: Handler
      {method} +Logger()
      {method} +setup(): void
      {method} +addHandler(logger: Logger): void
      {method} +setLevel(level: int): void
      {method} +setConsoleOutput(val: boolean): void
    }
  }
  package "PlayerAudience-Client" <<Rectangle>>{  
    class "PlayerAudienceClientExchange" as pace <<Observer>>{
      {field} +sessionCookie: Cookie
      {field} +hasVoted: boolean
      {field} +selectedDecision: StoryEvent
      {field} +possibleDecisions: StoryEvent[]
      {method} +PlayerAudienceClientExchange()
      {method} +update(): void
      {method} +sendSelectedDecision(): StoryEvent 
    }

    class "PlayerAudienceView" as pav {
      {method} +PlayerAudienceView()
    }
  }
  ss -- msl
  msl - cm
  msl -left- pe
  pe -left- api
  sl ... cm
  sl ... msl
  sl ... api
  sl ... ss
  pace - pav
  api "1" <-up- "n" pace : observes
}
@enduml