@startuml
left to right direction


rectangle "Moderator-Client" {
    usecase "Start Application" as start
}

actor "Moderator" as m
actor "ServerLogic" as s

m --> start
start --> s





/'
rectangle "Moderator-Client" {
    
    usecase "Start Application" as s
    usecase "Show Intro" as ia
    usecase "Show Mainmenu" as mm
    usecase "Show Options" as so
    usecase "End Application" as ea
    usecase "Start Offline-Game" as og
    together {
    usecase "Connect to Server" as cs
    usecase "Start game" as sg
    }
}
actor "Moderator" as m
actor "Server" as se
'actor "PlayerAudience" as p



m -right-> s
ia .down.> s : <<extend>>
s .right.> mm : <<include>>
so .down.> mm : <<extend>>
cs .down.> sg : <<include>>
mm ..> cs : <<include>>
ea ..> mm : <<extend>>
cs -left-> se
mm ..> og : <<include>>
'/

@enduml