@startuml
(*) --> "There is a company party coming up."
--> "The tests have revealed a few bugs, \n but there is also the company party. "
if "Do you attend the company party?" then 
-[#blue,dotted]-> [You attend the company party] "You are at the company party."

else 
--> [No, you continue to work on the project] "You continue to work on the project. \n Your stats change: \n +2 programming"
-[#blue,dotted]-> "A voluntary training course is coming up."

@enduml