@startuml
(*) --> "Do you want to participate in a company internship?"
if "" then
--> [Yes, gaining experience is always good!] "+1 programming \n +1 analytics \n +1 communication" as ja
else
--> [No, I have already learned everything \n I need to know during my studies.] "Through many parties in your spare \n time your partying will increase:\n +3 partying " as nein

ja --> "You have successfully completed your studies." as a
nein --> a





-[#blue,dotted]-> " "



@enduml