@startuml
(*) --> "Your company offers voluntary training, do you take part in it?"

if "" then
--> [Yes] "You unlock your sidepet, \n and the pet helps you with future decisions.\n Additionally you get \n+1 programming" as a1
else
--> [No] "No I already had this topic during my studies." as a2
else 
--> [No, I need a vacation first] "You take a week off." as a3
endif

-[#blue,dotted]-> "The German government has contacted you and would like to see changes to the Corona App" as app
a2 -[#blue,dotted]-> app
a1 -[#blue,dotted]-> app
@enduml