@startuml
(*) --> "The project is near completion, \n only the code review is missing." as ende
if "" then 
--> [Sure. \n Sidekickpet:"A review is important"] "+2 analytics \n +2 communication." as good
else 
--> [Nah, the test runs through. \n Alles gut soweit.] "-2 analytics \n -2 communication."
-[#blue,dotted]-> "The project has been completed, now the best employees are rewarded with a workshop in Hawaii." as shop
good -[#blue,dotted]-> shop
@enduml