@startuml
'Note: the project is not final, just a filler at the moment
(*) --> "The aminoa government calls and requests changes to the CoronaApp" as app
if "" then 
--> [You don't feel like it and just hang up.] "You get stats: \n -3 communication" as a1
else 
--> [You implement the \n desired change] "You get stats: \n +2 programming" as a2
else
if "The change is not feasible"
--> [You inform your customer] "You receive stats: \n +1 communication" as b1
else 
--> [You simply do not implement the change \n without informing the customer] "You will receive stats: \n -1 communication"
-[#blue,dotted]-> "A bug has surfaced." as bug 
a1 -[#blue,dotted]-> bug
a2 -[#blue,dotted]-> bug
b1 -[#blue,dotted]-> bug
@enduml