@startuml
(*) --> "Willst du an einem Firmenpraktikum teilnehmen?"
if "" then
--> [Ja, gerne] "Charakter erhält Stats" as ja
else
--> [Nein, keine Lust] "Charakter erhält keine Stats" as nein

ja --> Abschluss Studium
nein --> Abschluss Studium





'-[#blue,dotted]-> "   "



@enduml