@startuml
(*) --> "Abluss Studium" as as
--> "... ein halbes Jahr vergeht ..."
--> "Du hast eine Arbeitsstelle bei NewTec angenommen"
--> "Dein Chef hat einen neuen Auftrag der Bundesregierung übernommen, \n es geht um die neue CoronaApp" as a1
if "" then
--> [Du frägst deinen Mentor] "Character erhält Stat \n +2 communication" as a
else
--> [Googeln nach der Lösung] " " as b
else
--> [Einfach loslegen]" " as c

a --> "Random" as r







'-[#blue,dotted]-> "   "



@enduml