@startuml
(*) --> "You are still missing an elective subject at the end of your studies."
if "Which one will\n you choose?" then
--> [Introduction to Bali] "You have successfully completed \n  your elective subject.\n Your stats change: \n+2 programming \n +1 analytics" as bali
else
--> [Requirements\nEngineering] "You have successfully completed \n your elective subject.\n Your stats change: \n+1 programming \n +2 analytics" as re
else
--> [Introduction to \n Software Architectures] "You have successfully completed \n your elective subject.\n Your stats change: \n+3 analytics" as esa
else
--> [Usability as\nsuccess factor] "You have successfully completed \n your elective subject.\n Your stats change: \n+1 analytics \n +2 communication" as usf

usf -[#blue,dotted]-> "Extracurricular Activity" as nextDecision
re -[#blue,dotted]-> nextDecision
bali -[#blue,dotted]-> nextDecision
esa -[#blue,dotted]-> nextDecision

@enduml