@startuml
(*) --> "You are at the company party." 
if "What is the first thing you want to do?" then 
--> [You talk \n with your colleagues] "Your colleagues \n will give you a few tips. \n Your stats change: \n +2 programming" as tipps
else 
--> [You talk \n with your mentor \n and your boss] "You enable additional dialog option\n for later decisions." as ent

else
-[#blue,dotted]-> [You find a seat\n and sit by yourself.] "You are thirsty and want to get something to drink." as alc
tipps -[#blue,dotted]-> alc
ent -[#blue,dotted]-> alc

endif
@enduml