@startuml
(*) --> "Character selection"
if "" then
--> [character 1] "Elective course" as wpf
else
--> [character 2] wpf
else
--> [character 3] wpf
else
--> [character 4] wpf
else
--> [character 5] wpf
else
--> [character 6] wpf
if "" then
--> [Introduction\nto Bali] "Company internship" as fpr
else
--> [Requirements\nEngineering] fpr
else
--> [Introduction to\nSoftware Architectures] fpr
else
--> [Usability as\nsuccess factor] fpr
if "" then
-> [yes] "Gain experience" as n
n -> "Graduation" as p
else
--> [no] p
p --> "First project" as ep
ep --> "First task" as ea
if "" then
--> [Ask\nmentor] "Write tests" as ts
else
--> [Search the internet] ts
else
--> [Just\ngo for it] ts
-[#blue,dotted]-> "   "
@enduml