@startuml
(*) --> "Abluss Studium" as as
--> "... ein halbes Jahr vergeht ..."
--> "Du hast eine Arbeitsstelle bei NewTec angenommen"
--> "Dein Chef hat einen neuen Auftrag der Bundesregierung übernommen, \n es geht um die neue CoronaApp" as a1
--> "Deine Aufgabe ist es die Benutzeroberfläche zu gestalten"
if "" then
--> [Du frägst deinen Mentor] "Du verbesserst \n deine communication Fähigkeit \n +1 communication \n decision +1" as a
else
--> [Googeln nach der Lösung] "Du verschwendest eine Menge Zeit \n aber löst das Problem \n decision 0" as b
else
--> [Einfach loslegen] "Das war wohl nix \n -1 decision" as c

a --> "Random \n r = programming + random + decision" as r
b --> r
c --> r

if "" then
--> [r >= 5] "+1 programming" as p1
else
--> [r < 5] "keine Verbesserung"

--> "Aufgabe abgeschlossen" as aa

p1 --> aa


-[#blue,dotted]-> "   "



@enduml