@startuml
(*) --> "Which one will you choose?"
if "" then
--> [Introduction to Bali] "+2 programming \n +1 analytics" as bali
else
--> [Requirements\nEngineering] "+1 programming \n +2 analytics" as re
else
--> [Introduction to \n Software Architectures] "+3 analytics" as esa
else
--> [Usability as\nsuccess factor] "+1 analytics \n +2 communication" as usf


usf -[#blue,dotted]-> "After completing the elective, you can enjoy your free time, or would you rather take part in a extracurricular activity?" as a
re -[#blue,dotted]-> a
bali -[#blue,dotted]-> a
esa -[#blue,dotted]-> a

/'
Wir stehen 1 Jahr vor Ende des Studiums
Du musst Dich für ein Wahlpflichtfach entscheiden.


'/

@enduml