@startuml
(*) --> "Mit welchem Charakter willst du das Spiel spielen?"
if "" then
--> [Charakter 1] "Harald \n Stats:\n Programming: 1 \n Analytics: 4\n Communication 3 \n Partying: 2" as char1
else
--> [Charakter 2] "Isolde \n Stats:\n Programming: 4 \n Analytics: 3\n Communication 1 \n Partying: 0" as char2
else
--> [Charakter 3] "Heribert \n Stats:\n Programming: 2 \n Analytics: 2\n Communication 2 \n Partying: 2" as char3
else
--> [Charakter 4] "Kevin \n Stats:\n Programming: 1 \n Analytics: 0\n Communication 2 \n Partying: 5" as char4


--> "Dir fehlt zum Abschluß des Studiums noch ein Wahlpflichtfach." as a
char1 --> a
char2 --> a
char3 --> a

a-[#blue,dotted]-> " "
@enduml