@startuml
(*) --> "A voluntary training course is coming up, will you participate?"

if "" then
--> [Yes] "You can't meet your deadline,\n but your boss is happy about your commitment to\n expand your skill. You unlock your sidepet, \n and the pet helps you with future decisions.\n Additionally you get \n+1 programming" as a1
else
--> [No I already had this topic during my studies.] "You continue to work on the project, \n so you can meet your deadline without any issues." as a2
else 
--> [No, I need a vacation first] "You take a week off, but because of the vacation it\n is impossible to reach the deadline, \n your boss is angry. \n Your stats decrease: \n -2 analytics \n -2 communication" as a3
else 
--> [Additional dialog option: \n Your boss offers you a week vacation \n after your voluntary training] "You enjoy your vacation \n after your voluntary training. \n You don't get deadline problems \n because your boss has organized a substitute. \n You stats increase: \n+2 programming \n +2 analytics."
endif
'Note: project not final, its just a filler.
-[#blue,dotted]-> "The aminoa government has contacted you and would like to see changes to the WizzaApp" as app
a2 -[#blue,dotted]-> app
a1 -[#blue,dotted]-> app
a3 -[#blue,dotted]-> app
@enduml