@startuml
(*) --> "Graduate studies" as as
--> "... half a year passes ..."
--> "You have accepted a job at NewTec."
--> "Your boss has taken a new order from the federal government, \n it's about the new CoronaApp" as a1
--> "Your task is to design the user interface."
if "" then
--> [You ask your mentor] "You get to know your mentor, his name is Yaggaya."
--> "You improve \n your communication skills \n +1 communication \n 'decision +1'" as a
else
--> [You search for a suitable solution on HeapOverflow] "You waste a lot of time \n but solve the problem \n 'decision 0'" as b
else
--> [You just start, it will work out.] "You waste a lot of time without solving the problem. '-1 decision'" as c

a --> "Random \n r = programming + random + decision" as r
b --> r
c --> r

if "" then
--> [r >= 5] "+1 programming" as p1
else
--> [r < 5] "no improvement"

--> "Task completed" as aa

p1 --> aa


-[#blue,dotted]-> "After completing your task, you must now write the corresponding tests."



@enduml