@startuml
(*) --> "The project is completed, \n now the best employees are rewarded with a workshop in Hawaii." as shop
if "" then
--> [Anzahl aller Stats > 15] "Congratulations, \n you are invited to the workshop." as a
else 
--> [Anzahl aller Stats <= 15 && > 5] "Unfortunately it was not quite enough for you, \n good luck with your next project." as b
else
--> [Anzahl aller Stats < 5] "Congratulations, you got fired."
-[#blue,dotted]-> "THE END" as ende
a -[#blue,dotted]-> ende
b -[#blue,dotted]-> ende
@enduml