@startuml
(*) --> "You are thirsty and want to get something to drink, what do you take?" as alc
if "" then 
--> "One beer is enough for the evening." as genießen
genießen --> "You got through the evening.\n +1 partying" as party
else 
--> "A good old spezi is perfectly sufficient."
--> party
else 
--> "A few Tequilla shots will do it, \nafter all its for free, you should take advantage of it." as saufen
if "" then 
--> [partying + random > 8] "Due to your excellent party experience you are able to drink \n and survive the party without creating a stir: \n +3 partying" as alci
else 
--> [partying + random <= 8] "You bring a good atmosphere to the group, \n but your mentor and boss notice you \n negatively, because you are quite drunk.\n +3 partying \n -2 communication"
endif
--> "The party is over and you go home." as hause
party --> hause
alci --> hause
-[#blue,dotted]-> "A voluntary further education is pending, will you take part in it?"

@enduml