site_name: Pflichtenheft
nav:
 - ChangeHistory: changehistory.md
 - TableOfContent: index.md
 - QualityQuest: qualityquest.md
 - Glossar: glossar.md
 - Requirements: requirements.md
 - Use-Case: use-case-diagramme.md
 - StoryFlow: storyflow.md
 - UsedTools: usedtools.md
 
 
theme: readthedocs

markdown_extensions:
 - admonition
