@startuml

box "Network protocol relevance" #LightSteelBlue
actor "Moderator-Client" as m order 1
database "ServerLogic" as s order 2
end box
actor "PlayerAudience-Client" as p order 3



activate m
activate s

m -> s: RequestCloseSession
activate s
activate p
s -> p: Notify about ending session
deactivate s
deactivate p
s -> s: Clear logs
s --> m: SessionClosed


@enduml